version: "2.3"

services:
    postgres:
        container_name: dogs-postgres
        image: postgres:12
        environment: &db_env
          POSTGRES_DB: dogs-db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        volumes:
          - ./postgresql:/docker-entrypoint-initdb.d
        networks:
          - postgres

    redis:
      image: redis:7.2
      container_name: dogs-redis
      ports:
        - "6379:6379"
      volumes:
        - ./redis_data:/data
      command: ["redis-server", "--save", "60", "1", "--loglevel", "warning", "--maxmemory-policy", "allkeys-lru"]
      restart: unless-stopped

networks:
    postgres:
        driver: bridge
